<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tipe_kartu_model extends CI_Model
{

    public $table = 't_tipe_kartu';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select($this->table . '.*,' . 't_diskon.keterangan_diskon,t_extra_charge.keterangan_charge');
        $this->db->from($this->table);
        $this->db->join('t_diskon', 't_tipe_kartu.id_diskon=t_diskon.id', 'left');
        $this->db->join('t_extra_charge', 't_tipe_kartu.id_extra_charge=t_extra_charge.id', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('tipe_kartu', $q);
        $this->db->or_like('id_extra_charge', $q);
        $this->db->or_like('id_diskon', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select($this->table . '.*,' . 't_diskon.keterangan_diskon,t_diskon.nominal_diskon,t_extra_charge.extra_charge,t_extra_charge.keterangan_charge');
        $this->db->from($this->table);
        $this->db->join('t_diskon', 't_tipe_kartu.id_diskon=t_diskon.id', 'left');
        $this->db->join('t_extra_charge', 't_tipe_kartu.id_extra_charge=t_extra_charge.id', 'left');
        $this->db->order_by($this->id, $this->order);
        $this->db->like($this->table . '.id', $q);
        $this->db->or_like($this->table . '.tipe_kartu', $q);
        $this->db->or_like($this->table . '.id_extra_charge', $q);
        $this->db->or_like($this->table . '.id_diskon', $q);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Tipe_kartu_model.php */
/* Location: ./application/models/Tipe_kartu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-12-04 23:36:46 */
/* http://harviacode.com */
