<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_model extends CI_Model
{

    public $table = 'users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    public function enkripsi($plain_pasword)
    {
        $encpwd = password_hash($plain_pasword, PASSWORD_DEFAULT);
        return $encpwd;
    }
    public function login($email, $password)
    {

        $this->db->where('email', $email);
        $this->db->where('active', 1);
        $data = $this->db->get($this->table);
        if ($data->num_rows() > 0) {
            $datauser = $data->row();

            if (password_verify($password, $datauser->password)) {

                $this->session->set_userdata(
                    array(
                        'id_user' => $datauser->id,
                        'full_name' => $datauser->full_name,
                    )
                );

                return true;
            } else {
                // $this->session->set_flashdata('error_msg', 'password ferification =');
                return false;
                //gagal login
            }
        } else {
            //$this->session->set_flashdata('error_msg', 'num rows < 1');
            return false;

            //gagal login
        }
    }
    public function cekLogin()
    {
        if ($this->session->has_userdata('id_user')) {

            return true;
        } else {
            return false;
        }
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('full_name', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);

        $this->db->or_like('username', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('full_name', $q);

        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        //$this->db->delete($this->table);
        $this->db->update($this->table, array('active' => '0'));
    }
}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-12-05 03:20:15 */
/* http://harviacode.com */
